version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          # Check for updates to GitHub Actions every weekday
          interval: daily
      assignees:
          - perrin4869
    - package-ecosystem: gitsubmodule
      directory: /
      open-pull-requests-limit: 50
      schedule:
          # Check for updates to GitHub Actions every weekday
          interval: weekly
      ignore:
          # force following the latest HEAD and ignore tags othen than the pseudo-version
          # https://github.com/dependabot/dependabot-core/issues/1639#issuecomment-3991678824
          - dependency-name: "*"
            versions: ["> 0.0.0"]
