#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"   )" >/dev/null 2>&1 && pwd   )"

echo "Upgrade vim-import-size";
( cd $DIR/vim/pack/default/start/vim-import-size && npm install )

echo "Install coc.nvim";
( cd $DIR/vim/pack/default/start/coc.nvim && npm install )

( cd $DIR/gitflow && make prefix=$HOME/.local install )
