#!/bin/sh
lock() {
    i3lock
}

SYSD=$(command -v systemctl)

suspend() {
    if [[ $SYSD ]]; then
        systemctl suspend
    else
        dbus-send --system --print-reply --dest="org.freedesktop.UPower" /org/freedesktop/UPower org.freedesktop.UPower.Suspend
    fi
}

hibernate() {
    if [[ $SYSD ]]; then
        systemctl hibernate
    else
        dbus-send --system --print-reply --dest="org.freedesktop.UPower" /org/freedesktop/UPower org.freedesktop.UPower.Hibernate
    fi
}

reboot() {
    if [[ $SYSD ]]; then
        systemctl reboot
    else
        dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
    fi
}

shutdown() {
    if [[ $SYSD ]]; then
        systemctl poweroff
    else
        dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
    fi
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && suspend
        ;;
    hibernate)
        lock && hibernate
        ;;
    reboot)
        reboot
        ;;
    shutdown)
        shutdown
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
