#!/bin/bash
############################
# install
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

DIR=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
LOCAL_BIN_DIR=~/.local/bin

# list of files/folders to symlink in homedir
DOTFILE="bashrc zshrc sandboxrc git-completion.bash gitconfig git_ps1.bash vim vimrc gvimrc gitignore_global tmux.conf bash_profile screenrc latexmkrc powerline ctags ctags.d Xresources picom.conf xinitrc xprofile p10k.zsh"

##########

# change to the dotfiles directory
echo -n "Changing to the $DIR directory ..."
cd $DIR
echo "done"

for FILE in $DOTFILES; do
    echo "Creating symlink to $FILE in home directory."
    ln -sf $DIR/$FILE ~/.$FILE
done

# install config files
mkdir -p ~/.config
for file in config/*; do
    # Here $FILE looks like: $FILE=config/foo
    echo "Creating symlink to $FILE in .config directory."
    ln -sf $DIR/$FILE ~/.$FILE
done

ln -sf $DIR/vim ~/.config/nvim
ln -sf $DIR/vimrc ~/.config/nvim/init.vim

mkdir -p $LOCAL_BIN_DIR

mkdir -p ~/.config/i3
ln -sf $DIR/i3.config ~/.config/i3/config
ln -sf $DIR/chpwr $LOCAL_BIN_DIR

mkdir -p ~/.config/i3blocks
ln -sf $DIR/i3blocks-contrib ~/.config/i3blocks/blocks

mkdir -p ~/.config/sxhkd
ln -sf $DIR/sxhkdrc ~/.config/sxhkd

mkdir -p ~/.config/mpv
ln -sf $DIR/mpv.conf ~/.config/mpv

mkdir -p ~/.config/zathura
ln -sf $DIR/zathurarc ~/.config/zathura

mkdir -p ~/.config/ranger
ln -sf $DIR/rifle.conf ~/.config/ranger

mkdir -p ~/.config/qutebrowser
ln -sf $DIR/qutebrowser/autoconfig.yml ~/.config/qutebrowser

ln -sf $DIR/rofi ~/.config
ln -sf $DIR/rofi/modi/rofi-pass-modi/rofi-pass-modi $LOCAL_BIN_DIR

mkdir -p ~/.urxvt/ext
ln -sf $DIR/urxvt/urxvt-resize-font/resize-font ~/.urxvt/ext
ln -sf $DIR/urxvt/urxvt-perls/keyboard-select ~/.urxvt/ext
ln -sf $DIR/urxvt/urxvt-perls/deprecated/url-select ~/.urxvt/ext

# modify using these commands
# xdg-mime default mpv.desktop video/x-matroska
# xdg-mime query filetype foo.mkv
ln -sf $DIR/mimeapps.list ~/.config

# move executable files to bin
echo "Moving executable files into $LOCAL_BIN_DIR directory"
mkdir -p $LOCAL_BIN_DIR
ln -s $DIR/git_diff_wrapper $LOCAL_BIN_DIR
ln -s $DIR/i3-get-window-criteria $LOCAL_BIN_DIR
ln -s ~/.vim/pack/default/start/vim-themis/bin/themis $LOCAL_BIN_DIR

# pulsemixer
ln -sf $DIR/pulsemixer/pulsemixer ~/.local/bin

echo "Install powerline regardless of OS"
pip install --user --upgrade powerline-status
ln -s $(pip show powerline-status | grep 'Location' | rev | cut -d' ' -f 1 | rev)/powerline/bindings/tmux/powerline.conf ~/.local/powerline.conf

echo "Initializing submodules..."
git submodule update --recursive --init
./build

vim -c 'CocInstall -sync coc-json coc-html coc-tsserver coc-metals coc-ultisnips coc-omni coc-css|q'

#install fonts
ln -sf $DIR/fonts/*.ttf ~/.local/share/fonts
fc-cache -f

# install fzf
ln -sf $DIR/fzf ~/.fzf
./fzf/install --all

# sbt configuration
SBT_CONFIG_DIR=~/.sbt/1.0
mkdir -p $SBT_CONFIG_DIR
ln -sf $DIR/sbt/global.sbt $SBT_CONFIG_DIR

ln -sf /bin/dash $LOCAL_BIN_DIR

# install xwinwrap
( cd xwinwrap && make && ln -sf "$(pwd)/xwinwrap" $LOCAL_BIN_DIR )

ln -sf $DIR/ohmyzsh ~/.oh-my-zsh
ln -sf $DIR/sandbox ~/.oh-my-zsh/custom/plugins
ln -sf $DIR/zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins
ln -sf $DIR/powerlevel10k ~/.oh-my-zsh/custom/themes

# install ccls
( cd ccls && \
  cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release && \
  cmake --build Release && \
  ln -sf "$(pwd)/Release/ccls" $LOCAL_BIN_DIR )

# install coursier
ln -sf $DIR/coursier/cs-x86_64-pc-linux $LOCAL_BIN_DIR/cs
ln -sf $DIR/coursier/coursier $LOCAL_BIN_DIR/coursier

# https://scalameta.org/metals/docs/editors/vim.html#generating-metals-binary
cs bootstrap \
  --java-opt -Xss4m \
  --java-opt -Xms100m \
  --java-opt -Dmetals.client=vim-lsc \
  org.scalameta:metals_2.12:0.9.0 \
  -r bintray:scalacenter/releases \
  -r sonatype:snapshots \
  -o $LOCAL_BIN_DIR/metals-vim -f

dconf load /desktop/ibus/ < $DIR/ibus.dconf
