#!/bin/bash
############################
# install
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

dir=~/dotfiles # dotfiles directory
dotfiles="git-completion.bash gitconfig git_ps1.bash vim vimrc gvimrc gitignore_global tmux.conf irssi bash_profile screenrc latexmkrc powerline eslintrc ackrc" # list of files/folders to symlink in homedir

##########

# change to the dotfiles directory
echo -n "Changing to the $dir directory ..."
cd $dir
echo "done"

for file in $dotfiles; do
    echo "Creating symlink to $file in home directory."
    ln -sf $dir/$file ~/.$file
done

#install config files
mkdir -p ~/.config
for file in config/*; do
    # Here $file looks like: $file=config/foo
    echo "Creating symlink to $file in .config directory."
    ln -sf $dir/$file ~/.$file
done

#install fonts
mkdir -p ~/.local/share/fonts
for file in fonts/*; do
    # Here $file looks like: $file=fonts/foo
    echo "Creating symlink to $file in .config directory."
    ln -sf $dir/$file ~/.local/share/$file
done

#move executable files to bin
echo "Moving executable files into ~/.local/bin directory"
mkdir -p ~/.local/bin
ln -s $dir/git_diff_wrapper ~/.local/bin
ln -s ~/.vim/bundle/vim-themis/bin/themis ~/.local/bin

echo "Install powerline regardless of OS"
pip install --user --upgrade powerline-status
ln -s $(pip show powerline-status | grep 'Location' | rev | cut -d' ' -f 1 | rev)//powerline/bindings/tmux/powerline.conf ~/.local/powerline.conf

echo "Initializing submodules..."
git submodule update --recursive --init
./build

if [[ -x $(which fc-cache) ]]; then
    echo "Loading fonts..."
    fc-cache -vf
fi
