#!/bin/bash

# Get all updates from the server before anything else
echo "Pulling changes";
git pull

# Update all submodules
echo "Upgrade all submodules";
git subup

echo "Upgrade powerline"
pip install --user --upgrade powerline-status

./build
