#!/bin/bash

export TERMINAL=$([[ -x $(which urxvt256c 2> /dev/null)  ]] && echo urxvt256c || echo urxvt) # in slackware there are two builds of urxvt
export FILE=ranger
export BROWSER=chromium

export GTK_IM_MODULE=xim # makes ibus work with chromium/chrome (ibus fails)
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus # makes ibus work with qutebrowser (xim fails)

sxhkd &
blueman-applet &
dunst &
xscreensaver -no-splash &
udiskie --tray &
ibus-daemon --xim -d -r
compton -b --config ~/.compton.conf
setxkbmap -option compose:ralt

[ -x $HOME/.layout.sh ] && $HOME/.layout.sh

BACKGROUND_VIDEO=~/.config/background.mkv

if [[ -e $BACKGROUND_VIDEO ]]; then
  while read -r geometry;
  do
    xwinwrap -ni -s -b -ov -g $geometry -d -- mpv "$BACKGROUND_VIDEO" --no-audio --loop inf --wid WID;
  done < <(xrandr | sed "s/primary //" | grep -e '[0-9]\{4\}x[0-9]\{4\}' | grep ' connected' | cut -f 3 -d ' ' | sort -u) # requries bash over sh
  # normalizes primary screens, which appear in the third column, and filters out invalid dimensions and positions
fi
