#!/bin/sh

export TERMINAL=$([[ -x $(which urxvt256c 2> /dev/null)  ]] && echo urxvt256c || echo urxvt) # in slackware there are two builds of urxvt
export FILE=ranger
export BROWSER=chromium

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

sxhkd &
ibus-daemon --xim -d -r
compton -b --config ~/.compton.conf
setxkbmap -option compose:ralt
