#!/bin/bash

export TERMINAL="${TERMINAL:-kitty}"
export FILE="${FILE:-ranger}"
export BROWSER="${BROWSER-firefox}"

export GTK_IM_MODULE=xim # makes ibus work with chromium/chrome (ibus fails)
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus # makes ibus work with qutebrowser (xim fails)
export GLFW_IM_MODULE=ibus # kitty

if [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then
  export $(dbus-launch --exit-with-x11)
fi

sxhkd &
blueman-applet &
dunst &
xscreensaver -no-splash &
udiskie --tray &
redshift-gtk &
ibus-daemon --xim -d -r
picom -b --config ~/.picom.conf
setxkbmap -layout us -option compose:ralt

# If autorandr-launcher is installed (presumably because udev was not) then daemonize
command -v autorandr-launcher && autorandr-launcher --daemonize

if [[ -e "/etc/slackware-version" ]]; then
  sun_gtk &
fi

# bashism
# a monitor may be connected but not have a resolution
# match the resultion format with grep to ensure we check a monitor that is being used
if [[ "$(xrandr | grep " connected" | grep -E '[0-9]{1,4}x([0-9]{1,4})' | head -n 1)" =~ [0-9]{1,4}x([0-9]{1,4})\+[0-9]{1,4}\+[0-9]{1,4} && "${BASH_REMATCH[1]}" -gt "1080" ]];
then
  xrdb -merge $HOME/.Xresources.hidpi
fi

[ -x $HOME/.layout.sh ] && $HOME/.layout.sh

BACKGROUND_VIDEO=~/.config/background.mkv

if [[ -e $BACKGROUND_VIDEO ]]; then
  while read -r geometry;
  do
    xwinwrap -ni -s -b -ov -g $geometry -d -- mpv "$BACKGROUND_VIDEO" --no-audio --loop inf --wid WID;
  done < <(xrandr | sed "s/primary //" | grep -e '[0-9]\{4\}x[0-9]\{4\}' | grep ' connected' | cut -f 3 -d ' ' | sort -u) # requries bash over sh
  # normalizes primary screens, which appear in the third column, and filters out invalid dimensions and positions
fi
