local yall = require('yall')
local packadd = vim.cmd.packadd

yall.very_lazy(function()
	packadd('vim-caser')
	packadd('vim-illuminate')
	packadd('vim-floaterm')
	packadd('vim-fugitive')
	packadd('tagbar')
	packadd('vim-speeddating')
	packadd('vim-dispatch')
	packadd('vim-abolish')
	packadd('targets.vim')
	packadd('vim-exchange')
	packadd('vim-easy-align')
end)

yall.on_bufreadpre(function()
	packadd('ragtag')
	packadd('vim-sleuth')
	packadd('vim-gutentags')
end)

yall.on_insert(function()
	packadd('vim-fat-finger')
end)
