local defer = require('defer')
defer.on_load('refactoring', function()
	require('refactoring').setup()
end)
defer.pack('refactoring', 'refactoring.nvim')
defer.hook('refactoring')
defer.cmd('Refactor', 'refactoring')
