require("nvim-treeclimber").setup({})

vim.keymap.set("n", "<leader>k", "<Plug>(treeclimber-show-control-flow)", {})
vim.keymap.set({ "x", "o" }, "i.", "<Plug>(treeclimber-select-current-node)", {})
vim.keymap.set({ "x", "o" }, "a.", "<Plug>(treeclimber-select-expand)", {})
vim.keymap.set({ "n", "x", "o" }, "<M-e>", "<Plug>(treeclimber-select-forward-end)", {})
vim.keymap.set({ "n", "x", "o" }, "<M-b>", "<Plug>(treeclimber-select-backward)", {})
vim.keymap.set({ "n", "x", "o" }, "<M-h>", "<Plug>(treeclimber-select-previous)", {})
vim.keymap.set({ "n", "x", "o" }, "<M-j>", "<Plug>(treeclimber-select-shrink)", {})
vim.keymap.set({ "n", "x", "o" }, "<M-k>", "<Plug>(treeclimber-select-parent)", {})
vim.keymap.set({ "n", "x", "o" }, "<M-l>", "<Plug>(treeclimber-select-next)", {})
vim.keymap.set({ "n", "x", "o" }, "<M-L>", "<Plug>(treeclimber-select-grow-forward)", {})
vim.keymap.set({ "n", "x", "o" }, "<M-H>", "<Plug>(treeclimber-select-grow-backward)", {})
vim.keymap.set({ "n", "x", "o" }, "<M-[>", "<Plug>(treeclimber-select-siblings-backward)", {})
vim.keymap.set({ "n", "x", "o" }, "<M-]>", "<Plug>(treeclimber-select-siblings-forward)", {})
vim.keymap.set({ "n", "x", "o" }, "<M-g>", "<Plug>(treeclimber-select-top-level)", {})
