#!/usr/bin/env bash

if [ -z $@ ]; then
	shopt -s nullglob globstar
	prefix=${PASSWORD_STORE_DIR-$HOME/.password-store}
	password_files=( "$prefix"/**/*.gpg )
	password_files=( "${password_files[@]#"$prefix"/}" )
	password_files=( "${password_files[@]%.gpg}" )
	printf '%s\n' "${password_files[@]}"
else
	[[ -n $@ ]] && pass show -c "$@" >/dev/null
fi
