#!/bin/sh

set -eu

DEP="$1"
NEW_VERSION="$2"

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" 2>/dev/null && pwd)
VERSION_FILE="$SCRIPT_DIR/../.external_versions/$DEP"

echo "$NEW_VERSION" > "$VERSION_FILE"
