#!/bin/sh

set -euo pipefail

DEP="$1"
NEW_VERSION="$2"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
VERSION_FILE="$SCRIPT_DIR/../.external_versions/$DEP"

echo "$NEW_VERSION" > "$VERSION_FILE"
