vim.api.nvim_create_user_command("OsvLaunch", function()
	require("osv").launch({ port = 8086 })
end, { desc = "Launch osv" })

vim.api.nvim_create_user_command("OsvStop", require("osv").stop, { desc = "Stop osv" })

vim.keymap.set("n", "<C-g>x", function()
	vim.cmd(".source")
end, { noremap = true, buffer = true, silent = true, desc = "execute lua lua" })
vim.keymap.set("n", "<C-g>X", function()
	vim.cmd("source %")
end, { noremap = true, buffer = true, silent = true, desc = "execute lua file" })
vim.keymap.set("x", "<C-g>x", function()
	vim.cmd("'<'>source")
end, { noremap = true, buffer = true, silent = true, desc = "execute lua visual" })
